### ISSUE TITLE
Passing array for params does not work

### ISSUE THREAD

**Issue by mailaneel** [ice-services/moleculer-repl#3]
Using below 
`call users.get --userIds "a1234" --userIds 'a5678' ` 

sends
`{ userIds: { '0': "a1234", '1': "a5678" } }`

Once I change 
https://github.com/ice-services/moleculer-repl/blob/9769af1f9da8f47369b5c0cd498201b522bcdfdd/src/index.js#L35 to have below code it 

above to this
 ```js
if (Array.isArray(value))
			res[key] = value;
   else if (typeof(value) == "object")
			res[key] = convertArgs(value);
...
```

sends
`{ userIds: ["a1234", "a5678" ] }`

**Comment by icebob** [comment]
Great. Could you create a PR with the fix?

**Comment by mailaneel** [comment]
sure

**Comment by mailaneel** [comment]
PR created
https://github.com/ice-services/moleculer-repl/pull/4

**Comment by icebob** [comment]
Thanks!, I merged
